leftnav:
- identifier: 638cc0c5-cd7b-7ee8-8634-1db9eed28874
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: bbb46842-8cfc-91fd-62a1-b42347077e6c
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: 58220f64-d4bd-b996-26f6-83d5791796b9
  name: Readings
  pageRef: /pages/readings
  weight: 30
- identifier: ab5f7b79-26cb-16b9-4abf-0eeb8cde37c1
  name: Study Questions
  pageRef: /pages/lecture-summaries
  weight: 40
- identifier: fa6829d1-52ff-e7a1-38cf-619934efb184
  name: Assignments
  pageRef: /pages/assignments
  weight: 50
